### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by jnapolitan** [jnapolitan/Towncloud#2]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds (maybe not necessary for this clone?)

**Comment by andywynkoop** [comment]
- [ ] I'd prefer to sign up for this site over Splicewise
- [ ] Logo should be clickable and redirect to `/`
- [ ] For nav buttons, the entire `li` should be clickable (not just the text)
- [ ] Excellent privacy policy
- [ ] On landing page, center of the page should be white instead of grey
- [ ] Session modal transition is a little shaky, not too big of a deal but if you put the transition on position it might fix this
- [ ] Username should probably be case in-sensitive (so I can't sign up with the same username with different casing)
- [ ] Going to a random route, like `/banana`, should either redirect me back to `/` or `/splash`, or show a 404 page
- [ ] Remove all console.logs in production
